[dotrix.link]
".config/themer/akame-ga-kill" = "akame-ga-kill" 
".config/themer/kill-la-kill" = "kill-la-kill"
".config/themer/rain" = "rain"
".config/themer/snow" = "snow"
".config/themer/templates" = "templates"
".config/themer/ukraine" = "ukraine"
