#!/usr/bin/env bash

if [ "$GDMSESSION" == "xubuntu" ]; then
    exec xfce4-session-logout
else
    res=$(rofi -p "> " -dmenu < ~/.config/i3/scripts/powermenu)

    if [ $res = "logout" ]; then
	   i3-msg exit
    fi
    if [ $res = "restart" ]; then
	   dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Reboot" boolean:true
    fi
    if [ $res = "shutdown" ]; then
	   dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true
    fi
    if [ $res = "lock" ]; then
           dm-tool lock
    fi
    exit 0
fi
